In [1]:
!pip install tensorflow


Defaulting to user installation because normal site-packages is not writeable


In [2]:
!pip install matplotlib


Defaulting to user installation because normal site-packages is not writeable


In [3]:
!pip install pickle


Defaulting to user installation because normal site-packages is not writeable


ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle


In [4]:
!pip install pickle

Defaulting to user installation because normal site-packages is not writeable


ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle


In [5]:
!pip install sklearn


Defaulting to user installation because normal site-packages is not writeable
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'


  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-packag

In [6]:
!pip install scikit-learn


Defaulting to user installation because normal site-packages is not writeable


In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.8.0+cpu'

In [8]:
## Introduction to tensors (A way to represent a multi dimensional data)

scaler = torch.tensor(7)
scaler


tensor(7)

In [9]:
##Vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [10]:
##Matrix

matrix = torch.tensor([[2,3],[4,5]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[2, 3],
        [4, 5]])
2
torch.Size([2, 2])


In [11]:
##Tensor 
ten = torch.tensor([[[1,2,3],
                    [4,5,6],
                    [7,8,9]]])

ten


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
ten.ndim


3

In [13]:
ten.shape


torch.Size([1, 3, 3])

In [14]:
## Random Tensors (random tensors are important because the way neural networks learn is that they start full random numbers and then they are arranged to represent data better )
random_Tensor = torch.rand(3,4)


In [15]:
base = torch.zeros([2,3])
base

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
r1 = torch.rand_like(base)
r1

tensor([[0.5315, 0.3106, 0.7321],
        [0.6427, 0.8331, 0.7110]])

In [17]:
r2 = torch.randn_like(base)
r2

tensor([[ 0.6957,  0.6348,  0.4670],
        [-0.5055, -1.3773, -0.9632]])

In [18]:
random_tensor = torch.rand([10,10,10])
random_tensor
## 10*10*10 randon uniformally distributed values

tensor([[[9.6203e-01, 1.3462e-01, 6.3445e-01, 7.5197e-02, 2.1489e-01,
          7.6978e-01, 6.1872e-02, 8.2483e-01, 9.1658e-01, 6.5598e-02],
         [4.0504e-01, 5.9900e-01, 5.8573e-01, 8.2629e-01, 4.6492e-01,
          2.7152e-01, 7.3286e-01, 9.2253e-01, 7.7837e-01, 5.1241e-01],
         [9.4306e-01, 3.2138e-01, 4.2380e-01, 2.7702e-01, 5.3010e-01,
          5.3727e-01, 8.4386e-01, 2.5118e-01, 1.9384e-01, 5.1542e-01],
         [3.7614e-01, 5.7758e-01, 2.9910e-01, 9.8284e-01, 6.3423e-01,
          2.5410e-01, 3.1493e-03, 9.1217e-01, 3.5085e-01, 1.9742e-01],
         [9.5987e-01, 1.8540e-01, 6.0197e-01, 1.6916e-01, 4.6430e-02,
          8.2562e-01, 4.3003e-01, 7.0842e-01, 7.2267e-01, 3.1232e-02],
         [2.6132e-01, 5.8540e-01, 3.2122e-01, 6.5991e-01, 3.7803e-01,
          5.9860e-01, 6.3416e-01, 6.7642e-01, 4.9702e-01, 4.3517e-01],
         [2.6351e-01, 7.8287e-01, 5.6194e-01, 5.1708e-01, 3.6137e-01,
          5.7692e-01, 9.9315e-01, 9.8486e-01, 5.9170e-01, 6.7842e-01],
         [8.7

In [19]:
##Color selection in RBG 

random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#Zeros and ones 

In [20]:
random_zeros = torch.zeros([2,3])
random_zeros 

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
random_ones = torch.ones([2,3])
random_ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [22]:
# Each element has a probability of 0.5 to become 1
probs = torch.full((2, 4), 0.5)
bernoulli_ones_zeros = torch.bernoulli(probs)
print(bernoulli_ones_zeros)

tensor([[0., 0., 1., 1.],
        [1., 0., 0., 0.]])


In [23]:
probs = torch.full((2, 4), 0.5)
probs

tensor([[0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000]])

In [24]:
## Creating a range of rensors

torch.range(0,10)

C:\Users\shiva\AppData\Local\Temp\ipykernel_11168\3094960297.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
num = torch.arange(start=0,end=1000,step=77)  
num

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [26]:
making_zeros = torch.zeros_like(num)
making_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
#Float 32 tensor 
float_32_tensor = torch.tensor([3.0,6.0,9.,])
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = torch.tensor([3.0,6.0,9.,] , dtype =  torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor.dtype

torch.float16

In [31]:
#OR
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
int_32_tensor = torch.tensor( [2.0 , 3.0 , 4.0],dtype = torch.int32)
int_32_tensor

tensor([2, 3, 4], dtype=torch.int32)

In [33]:
float_16_tensor*int_32_tensor

tensor([ 6., 18., 36.], dtype=torch.float16)

In [34]:
tens = torch.tensor([1,2,3])
tens+10


tensor([11, 12, 13])

In [35]:
tens-10

tensor([-9, -8, -7])

In [36]:
tens*10

tensor([10, 20, 30])

In [37]:
tens/10


tensor([0.1000, 0.2000, 0.3000])

In [38]:
#Matrix Multiplication

t1 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
t2 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(t1.shape , t1.ndim)
print(t1@t2)
matrix_mul = torch.matmul(t1,t2)
print(matrix_mul)

torch.Size([3, 3]) 2
tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])
tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])


In [39]:
## Element wise multiplication 

In [40]:
t1*t2

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [41]:
%%time
torch.matmul(t1, t2)

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [42]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

#torch.matmul(tensor_A, tensor_B) # (this will error)

In [43]:
# We can transpose one of them to actually satify the dimension condition (inner dimension should be same )
final_mult = torch.matmul(tensor_A , tensor_B.T)
final_mult

#3X2 2X3

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [44]:
final_mult_2 = torch.matmul(tensor_A.T , tensor_B)
final_mult_2

#2X3 3X2

tensor([[ 76., 103.],
        [100., 136.]])