<a href="https://colab.research.google.com/github/paradox-shivansh/Pytorch/blob/master/pytorch00a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensor Aggrigation (Min, Max, sum and etc)

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

Look how default datatype changes in the arange methord

In [3]:
x = torch.arange(0 , 100 , 1)
x.dtype

torch.int64

In [4]:
y = torch.arange(0 , 100 , 0.5)
y.dtype

torch.float32

In [5]:
torch.max(x) , torch.min(x)

(tensor(99), tensor(0))

In [6]:
torch.mean(x)

tensor(49.5000)

In [7]:
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(49.5000), tensor(49.5000))

##Positional MinMax

In [8]:
x.argmin() , x.argmax()

(tensor(0), tensor(99))

## Reshaping , Stacking , Squizing , Unsquizing

In [9]:
z = torch.arange(1. , 10.)
z , z.shape , z.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [10]:
# Add an extra dimension
z_reshaped = z.reshape(1 , 9)
z_reshaped , z_reshaped.shape , z.ndim , z_reshaped.ndim


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 1, 2)

In [11]:
# Change in view
a = z.view(1 , 9)
a , a.shape

# a and z share the same memory , means changes made in a will make changes in z

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [12]:
# Study more about it in the notes and how to implrmrnt it

In [13]:
# Permute
x_orignal = torch.rand(size = (224 , 224 , 3))
x_permuted = x_orignal.permute(2 , 0 , 1)
x_orignal.shape , x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

#INDEXING


In [14]:
import torch

In [15]:
n = torch.arange(1,10).reshape(1,3,3)
n , n.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [16]:
n[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
# index on middle bracket
n[0][0]

tensor([1, 2, 3])

In [18]:
n[0][0][0]

tensor(1)

In [19]:
n[0][0][1]

tensor(2)

# Pytorch and Numpy

In [20]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [21]:
tr = torch.ones(7)
np_tr = tr.numpy()
tr , np_tr

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [24]:
tr = tr + 1
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

## Reproducability (create random out of random)

In [25]:
torch.rand(3,3)

tensor([[0.4778, 0.9246, 0.7908],
        [0.1290, 0.7575, 0.6679],
        [0.8296, 0.9311, 0.4100]])

In [26]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5368, 0.7232, 0.9288, 0.9034],
        [0.4768, 0.7958, 0.7501, 0.8800],
        [0.6918, 0.1238, 0.6045, 0.2068]])
tensor([[0.3381, 0.2551, 0.2833, 0.8665],
        [0.1960, 0.9371, 0.3060, 0.3534],
        [0.1612, 0.3346, 0.4213, 0.4615]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [28]:
# Lets make some ram=ndom but reproducable tensors
import torch

# Set the random tensor
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [29]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [30]:
b = torch.arange(1 , 11 , 1)
print(b , b.device)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) cpu


In [33]:
b_on_tensor = b.to(device = 'cuda:0')
print(b_on_tensor , b_on_tensor.device)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [34]:
b.device

device(type='cpu')